<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPplxvUl\BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPplxvUl/BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerPplxvUl.legacy');

    return;
}

if (!\class_exists(BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerPplxvUl\BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer::class, BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer::class, false);
}

return new \ContainerPplxvUl\BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer([
    'container.build_hash' => 'PplxvUl',
    'container.build_id' => 'e98cd09a',
    'container.build_time' => 1679583614,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPplxvUl');
