<?php

namespace ContainerM9U6G9b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBewePlaceholder_ExtensionService extends BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'bewe_placeholder.extension' shared service.
     *
     * @return \BernhardWebstudio\PlaceholderBundle\Twig\PlaceholderExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 4).'/src/Twig/PlaceholderExtension.php';

        return $container->privates['bewe_placeholder.extension'] = new \BernhardWebstudio\PlaceholderBundle\Twig\PlaceholderExtension(($container->services['bewe_placeholder.provider'] ?? $container->load('getBewePlaceholder_ProviderService')));
    }
}
