<?php

namespace ContainerM9U6G9b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaceholderProviderControllerService extends BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'BernhardWebstudio\PlaceholderBundle\Controller\PlaceholderProviderController' shared service.
     *
     * @return \BernhardWebstudio\PlaceholderBundle\Controller\PlaceholderProviderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PlaceholderProviderController.php';

        $container->services['BernhardWebstudio\\PlaceholderBundle\\Controller\\PlaceholderProviderController'] = $instance = new \BernhardWebstudio\PlaceholderBundle\Controller\PlaceholderProviderController(($container->services['bewe_placeholder.provider'] ?? $container->load('getBewePlaceholder_ProviderService')));

        $instance->setContainer($container);

        return $instance;
    }
}
