<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJeuXqbq\BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJeuXqbq/BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJeuXqbq.legacy');

    return;
}

if (!\class_exists(BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJeuXqbq\BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer::class, BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer::class, false);
}

return new \ContainerJeuXqbq\BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer([
    'container.build_hash' => 'JeuXqbq',
    'container.build_id' => 'f6417d9e',
    'container.build_time' => 1679585067,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJeuXqbq');
