<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBkp4Nj5\TestsTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBkp4Nj5/TestsTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBkp4Nj5.legacy');

    return;
}

if (!\class_exists(TestsTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBkp4Nj5\TestsTestDebugProjectContainer::class, TestsTestDebugProjectContainer::class, false);
}

return new \ContainerBkp4Nj5\TestsTestDebugProjectContainer(array(
    'container.build_hash' => 'Bkp4Nj5',
    'container.build_id' => 'c0779f0c',
    'container.build_time' => 1525374127,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBkp4Nj5');
