<?php

namespace ContainerPplxvUl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaceholderProviderControllerService extends BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'BernhardWebstudio\PlaceholderBundle\Controller\PlaceholderProviderController' shared service.
     *
     * @return \BernhardWebstudio\PlaceholderBundle\Controller\PlaceholderProviderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 5).'/src/Controller/PlaceholderProviderController.php';

        return $container->services['BernhardWebstudio\\PlaceholderBundle\\Controller\\PlaceholderProviderController'] = new \BernhardWebstudio\PlaceholderBundle\Controller\PlaceholderProviderController(($container->services['bewe_placeholder.provider'] ?? $container->load('getBewePlaceholder_ProviderService')));
    }
}
