<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'bewe_placeholder.provider' shared service.

return $this->services['bewe_placeholder.provider'] = new \BernhardWebstudio\PlaceholderBundle\Service\PlaceholderProviderService(($this->services['bewe_placeholder.generator.primitive'] ?? $this->services['bewe_placeholder.generator.primitive'] = new \BernhardWebstudio\PlaceholderBundle\Service\PrimitivePlaceholderGenerator('primitive', 10)));
