<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'bewe_placeholder.generator.sqip' shared service.

return $this->services['bewe_placeholder.generator.sqip'] = new \BernhardWebstudio\PlaceholderBundle\Service\SqipPlaceholderGenerator('sqip', 5);
