name: PHP Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install Composer dependencies
      run: composer install --dev --prefer-dist --no-progress --no-suggest --no-interaction
    
    # go to be sure in case its a 32 bit machine. Also, it is easier this way
    - name: Install primitive
      run: go get -u github.com/fogleman/primitive
    
    - name: Install NodeJS dependencies
      run: npm install

    - name: Run test suite
      run: ./bin/simple-phpunit install && composer run test
