name: PHP Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1

    - name: Install primitive
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        go get -u github.com/fogleman/primitive
      # primitive -V

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install Composer dependencies
      run: |
        composer install --dev --prefer-dist --no-progress --no-suggest --no-interaction
        ./bin/simple-phpunit install 
    
    - name: Install NodeJS dependencies
      run: npm install

    - name: Run test suite
      run: composer run test
