<?php

namespace Container7BLJv4J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBewePlaceholder_Generator_SqipService extends BernhardWebstudio_PlaceholderBundle_Tests_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'bewe_placeholder.generator.sqip' shared service.
     *
     * @return \BernhardWebstudio\PlaceholderBundle\Service\SqipPlaceholderGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Service/PlaceholderGeneratorInterface.php';
        include_once \dirname(__DIR__, 5).'/src/Service/AbstractNodeExecGenerator.php';
        include_once \dirname(__DIR__, 5).'/src/Service/SqipPlaceholderGenerator.php';

        return $container->services['bewe_placeholder.generator.sqip'] = new \BernhardWebstudio\PlaceholderBundle\Service\SqipPlaceholderGenerator('node_modules/.bin/sqip', 'node', 5);
    }
}
